<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.2.5</Version>
    <InformationalVersion>0.2.5</InformationalVersion>
  </PropertyGroup>
</Project>
