<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.3.0</Version>
    <InformationalVersion>0.3.0</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0" PrivateAssets="all" />
    <Protobuf Include="Protos\host.proto" GrpcServices="None" />
    <Protobuf Include="Protos\local_security.proto" GrpcServices="None" />
    <Protobuf Include="Protos\peer_security.proto" GrpcServices="None" />
    <Protobuf Include="Protos\peer_pairing.proto" GrpcServices="None" />
  </ItemGroup>
</Project>
